### ISSUE TITLE
Vue Action problem

### ISSUE THREAD

**Issue by Pokrt** [Yuyz0112/dewhale#293]
Hi, 
while trying dewhale i bumped into problem with my Action.  

``` js
 error: Uncaught (in promise) GraphqlResponseError: Request failed due to following response errors:
 - Could not resolve to an Issue with the number of 3.
    at file:///home/runner/.cache/deno/npm/registry.npmjs.org/@octokit/graphql/7.1.0/dist-node/index.js:113:13
    at eventLoopTick (ext:core/01_core.js:192:13)
    at async getConnectedPr (file:///home/runner/work/dewhale/dewhale/prompts/common.ts:117:26)
    at async composeWorkflow (file:///home/runner/work/dewhale/dewhale/prompts/common.ts:458:31)
    at async main (file:///home/runner/work/dewhale/dewhale/prompts/vue-ui-gen.ts:108:18)
Error: Process completed with exit code 1.
```

![Screenshot 2024-05-05 at 18-19-40 Homepage · Pokrt_dewhale@ee7f657](https://github.com/Yuyz0112/dewhale/assets/47066978/92231872-819e-4a28-b6c7-328cc5f4f5ab)

**Comment by adrianlzt** [comment]
same error here
