### ISSUE TITLE
Invalid image Error

### ISSUE THREAD

**Issue by ohizkiya** [Yuyz0112/dewhale#315]
I successfully cloned and set up project as a private repo. Everything works well including deploying to Cloudflare, as long as I stick to triggering the actions by creating issues with text only. However, if I include an example image I get the error below. Please see the stack trace. Any ideas?

`error: Uncaught (in promise) Error: 400 Invalid image.
      return new BadRequestError(status, error, message, headers);
             ^
    at Function.generate (https://deno.land/x/openai@v4.20.1/error.ts:71:14)
    at OpenAI.makeStatusError (https://deno.land/x/openai@v4.20.1/core.ts:409:21)
    at OpenAI.makeRequest (https://deno.land/x/openai@v4.20.1/core.ts:470:24)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async retryAsync.delay (file:///home/runner/work/ai_app_generation/ai_app_generation/prompts/common.ts:38:30)
    at async retryAsync (https://deno.land/x/retry@v2.0.0/retry/retry.ts:47:20)
    at async recall (https://deno.land/x/retry@v2.0.0/retry/retry.ts:44:12)
    at async retryAsync (https://deno.land/x/retry@v2.0.0/retry/retry.ts:58:14)
    at async recall (https://deno.land/x/retry@v2.0.0/retry/retry.ts:44:12)
    at async retryAsync (https://deno.land/x/retry@v2.0.0/retry/retry.ts:58:14)`

**Comment by ohizkiya** [comment]
@Yuyz0112 any chance you've run into this?
