### ISSUE TITLE
Failure in generative-ui step

### ISSUE THREAD

**Issue by devdjdjdj** [Yuyz0112/dewhale#317]
```
<img width="1172" alt="Screenshot 2024-06-04 at 1 04 36 AM" src="https://github.com/Yuyz0112/dewhale/assets/8934007/571bb3d9-42fe-44a6-8256-50c969a51f50">
```
```javascript

  user: {
    avatar_url: "https://avatars.githubusercontent.com/u/8934007?v=4",
    events_url: "https://api.github.com/users/***/events{/privacy}",
    followers_url: "https://api.github.com/users/***/followers",
    following_url: "https://api.github.com/users/***/following{/other_user}",
    gists_url: "https://api.github.com/users/***/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/***",
    id: 8934007,
    login: "***",
    node_id: "MDQ6VXNlcjg5MzQwMDc=",
    organizations_url: "https://api.github.com/users/***/orgs",
    received_events_url: "https://api.github.com/users/***/received_events",
    repos_url: "https://api.github.com/users/***/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/***/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/***/subscriptions",
    type: "User",
    url: "https://api.github.com/users/***"
  }
} undefined { login: "***" }
error: Uncaught (in promise) HttpError: Resource not accessible by integration - https://docs.github.com/rest/git/blobs#create-a-blob
    at file:///home/runner/.cache/deno/npm/registry.npmjs.org/@octokit/request/8.4.0/dist-node/index.js:125:21
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async requestWithGraphqlErrorHandling (file:///home/runner/.cache/deno/npm/registry.npmjs.org/@octokit/plugin-retry/6.0.1/dist-node/index.js:71:20)
    at async Job.doExecute (file:///home/runner/.cache/deno/npm/registry.npmjs.org/bottleneck/2.19.5/light.js:405:18)
Error: Process completed with exit code 1.
```

**Comment by ACEser** [comment]
我也是遇到这个错误
I also had the same problem

**Comment by dstn-idly** [comment]
same here
